-- 为 product_sku 表添加缺失的字段
-- 如果字段已存在，会报错但可以忽略

-- ========== 数据库 jiaoyi_0 ==========
USE jiaoyi_0;

-- product_sku_0
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_attributes TEXT COMMENT 'SKU属性（JSON格式）' AFTER sku_code;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_name VARCHAR(200) COMMENT 'SKU名称' AFTER sku_attributes;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_price DECIMAL(10,2) COMMENT 'SKU价格' AFTER sku_name;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_image VARCHAR(500) COMMENT 'SKU图片' AFTER sku_price;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'SKU状态' AFTER sku_image;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER status;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0 COMMENT '版本号' AFTER is_delete;

-- product_sku_1
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_attributes TEXT COMMENT 'SKU属性（JSON格式）' AFTER sku_code;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_name VARCHAR(200) COMMENT 'SKU名称' AFTER sku_attributes;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_price DECIMAL(10,2) COMMENT 'SKU价格' AFTER sku_name;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_image VARCHAR(500) COMMENT 'SKU图片' AFTER sku_price;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'SKU状态' AFTER sku_image;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER status;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0 COMMENT '版本号' AFTER is_delete;

-- product_sku_2
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_attributes TEXT COMMENT 'SKU属性（JSON格式）' AFTER sku_code;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_name VARCHAR(200) COMMENT 'SKU名称' AFTER sku_attributes;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_price DECIMAL(10,2) COMMENT 'SKU价格' AFTER sku_name;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_image VARCHAR(500) COMMENT 'SKU图片' AFTER sku_price;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'SKU状态' AFTER sku_image;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER status;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0 COMMENT '版本号' AFTER is_delete;

-- ========== 数据库 jiaoyi_1 ==========
USE jiaoyi_1;

ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_attributes TEXT COMMENT 'SKU属性（JSON格式）' AFTER sku_code;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_name VARCHAR(200) COMMENT 'SKU名称' AFTER sku_attributes;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_price DECIMAL(10,2) COMMENT 'SKU价格' AFTER sku_name;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_image VARCHAR(500) COMMENT 'SKU图片' AFTER sku_price;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'SKU状态' AFTER sku_image;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER status;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0 COMMENT '版本号' AFTER is_delete;

ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_attributes TEXT COMMENT 'SKU属性（JSON格式）' AFTER sku_code;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_name VARCHAR(200) COMMENT 'SKU名称' AFTER sku_attributes;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_price DECIMAL(10,2) COMMENT 'SKU价格' AFTER sku_name;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_image VARCHAR(500) COMMENT 'SKU图片' AFTER sku_price;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'SKU状态' AFTER sku_image;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER status;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0 COMMENT '版本号' AFTER is_delete;

ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_attributes TEXT COMMENT 'SKU属性（JSON格式）' AFTER sku_code;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_name VARCHAR(200) COMMENT 'SKU名称' AFTER sku_attributes;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_price DECIMAL(10,2) COMMENT 'SKU价格' AFTER sku_name;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_image VARCHAR(500) COMMENT 'SKU图片' AFTER sku_price;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'SKU状态' AFTER sku_image;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER status;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0 COMMENT '版本号' AFTER is_delete;

-- ========== 数据库 jiaoyi_2 ==========
USE jiaoyi_2;

ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_attributes TEXT COMMENT 'SKU属性（JSON格式）' AFTER sku_code;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_name VARCHAR(200) COMMENT 'SKU名称' AFTER sku_attributes;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_price DECIMAL(10,2) COMMENT 'SKU价格' AFTER sku_name;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS sku_image VARCHAR(500) COMMENT 'SKU图片' AFTER sku_price;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'SKU状态' AFTER sku_image;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER status;
ALTER TABLE product_sku_0 ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0 COMMENT '版本号' AFTER is_delete;

ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_attributes TEXT COMMENT 'SKU属性（JSON格式）' AFTER sku_code;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_name VARCHAR(200) COMMENT 'SKU名称' AFTER sku_attributes;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_price DECIMAL(10,2) COMMENT 'SKU价格' AFTER sku_name;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS sku_image VARCHAR(500) COMMENT 'SKU图片' AFTER sku_price;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'SKU状态' AFTER sku_image;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER status;
ALTER TABLE product_sku_1 ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0 COMMENT '版本号' AFTER is_delete;

ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_attributes TEXT COMMENT 'SKU属性（JSON格式）' AFTER sku_code;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_name VARCHAR(200) COMMENT 'SKU名称' AFTER sku_attributes;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_price DECIMAL(10,2) COMMENT 'SKU价格' AFTER sku_name;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS sku_image VARCHAR(500) COMMENT 'SKU图片' AFTER sku_price;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT 'SKU状态' AFTER sku_image;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除' AFTER status;
ALTER TABLE product_sku_2 ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0 COMMENT '版本号' AFTER is_delete;

